// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimRend.Models;

namespace SimRend.Migrations
{
    [DbContext(typeof(FondoContext))]
    [Migration("20181106223535_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("SimRend.Models.Solicitud", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("FechaActual");

                    b.Property<DateTime>("FechaEvento");

                    b.Property<string>("LugarEvento");

                    b.Property<int>("Monto");

                    b.Property<string>("NombreEvento");

                    b.Property<string>("Responsable");

                    b.HasKey("ID");

                    b.ToTable("Solicitud");
                });
#pragma warning restore 612, 618
        }
    }
}
